// Apoio só dos testes: espelha o `julgamentos.json` que o motor grava no
// ciclo, com domínios fictícios. Nenhum código de produção importa este arquivo.

export const JULGAMENTOS_DE_EXEMPLO = {
  tarefa: {
    nome: "sites_citados",
    modelo: "typesafe/jev-1.13-20261001",
    versao: "fd64eb78f2d9",
    fase: "sugestao",
    motivo: "placar abaixo do critério: 0 confirmações",
    placar: {
      confirmacoes: 0,
      firmes: 0,
      erros_entre_firmes: 0,
      trocas_no_mesmo_balde: 0,
      cobertura: 0.0,
    },
    caminhos: {
      permitidos: ["editorial_conquistado", "perfil_reivindicavel"],
      bloqueados: ["listagem_de_inventario", "editorial_fechado"],
      condicionais: ["parceria_comercial"],
    },
  },
  dominios: [
    {
      dominio: "guia-exemplo.com",
      url: null,
      titulo: null,
      origem: null,
      caminho: null,
      sugestao: {
        categoria: "editorial_conquistado",
        confianca_categoria: 0.8,
        ocupavel: "sim",
        confianca_ocupavel: 0.9,
        firme: true,
        brutos: [
          "raw/julgamento/guia-exemplo.com_categoria.json",
          "raw/julgamento/guia-exemplo.com_ocupavel.json",
        ],
      },
      citacoes: 2,
      prompts_distintos: 2,
    },
    {
      dominio: "regra-exemplo.com",
      url: null,
      titulo: null,
      origem: "regra",
      caminho: null,
      sugestao: null,
      citacoes: 1,
      prompts_distintos: 1,
    },
    {
      dominio: "reservas-exemplo.com",
      url: null,
      titulo: null,
      origem: null,
      caminho: null,
      sugestao: {
        categoria: "listagem_de_inventario",
        confianca_categoria: 0.8,
        ocupavel: "nao",
        confianca_ocupavel: 0.9,
        firme: true,
        brutos: [
          "raw/julgamento/reservas-exemplo.com_categoria.json",
          "raw/julgamento/reservas-exemplo.com_ocupavel.json",
        ],
      },
      citacoes: 1,
      prompts_distintos: 1,
    },
    {
      dominio: "feita-exemplo.com",
      url: null,
      titulo: null,
      origem: "pessoa",
      caminho: "editorial_fechado",
      sugestao: null,
      citacoes: 1,
      prompts_distintos: 1,
    },
    {
      dominio: "rival-exemplo.com",
      url: null,
      titulo: null,
      origem: "regra",
      caminho: "controlado_por_concorrente",
      sugestao: null,
      citacoes: 1,
      prompts_distintos: 1,
    },
    {
      dominio: "talvez-exemplo.com",
      url: null,
      titulo: null,
      origem: null,
      caminho: null,
      sugestao: {
        categoria: "editorial_conquistado",
        confianca_categoria: 0.8,
        ocupavel: "nao",
        confianca_ocupavel: 0.9,
        firme: false,
        brutos: [
          "raw/julgamento/talvez-exemplo.com_categoria.json",
          "raw/julgamento/talvez-exemplo.com_ocupavel.json",
        ],
      },
      citacoes: 1,
      prompts_distintos: 1,
    },
  ],
  resumo: {
    dominios: 6,
    regra: 2,
    pessoa: 1,
    modelo: 0,
    sugestao_firme: 2,
    em_duvida: 1,
    sem_resposta: 0,
  },
};
